<?php

/**
 * @file
 * Contains iln.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function iln_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the iln module.
    case 'help.page.iln':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Customisations') . '</p>';
      return $output;

    default:
  }
}
